### ISSUE TITLE
router bug

### ISSUE THREAD

**Issue by shayanfpg9** [CodingWithEnjoy/React-Css-Generator#1]
Hi, 👋
Bro this app is great but I found a big problem,

when you go to this address (https://codingwithenjoy.github.io/flexbox) it shows a 404 error page because you don't have any repository with this name in your github.
But when we go to your project web page (https://codingwithenjoy.github.io/React-Css-Generator/) it replaces the URL page to (https://codingwithenjoy.github.io),
so when we click on the flexbox button, it redirects us to (https://codingwithenjoy.github.io/flexbox) and also shows the result.

I think problem is in routing or when you redirect the page to (https://codingwithenjoy.github.io)

**Comment by CodingWithEnjoy** [comment]
Hi Shayan
Thank you for reporting this bug , I will fix it soon 🙋‍♂️
🙏🙏🙏
